### ISSUE TITLE
build bpftools error

### ISSUE THREAD

**Issue by joeycold** [facebookexperimental/ExtendedAndroidTools#10]
```make[1]: Leaving directory `/ExtendedAndroidTools/build/android/arm64/python'
touch build/android/arm64/python.done
mkdir -p build/android/arm64/xz
cd build/android/arm64/xz && /ExtendedAndroidTools/projects/xz/sources/configure --host=aarch64-linux-android --prefix=/ExtendedAndroidTools/out/android/arm64 LDFLAGS="-pie"
/bin/sh: 1: /ExtendedAndroidTools/projects/xz/sources/configure: not found
projects/xz/build.mk:17: recipe for target 'build/android/arm64/xz' failed
make: *** [build/android/arm64/xz] Error 127```
occur error when I chose docker script to build this.seems like xz sources dir doesn't have configure.

**Comment by michalgr** [comment]
Hi.

I double checked and I do see a configure script in xz sources. Does it help if you remove xz sources directory (`make remove-xz-sources`) and start again ?
