### ISSUE TITLE
Static bpftrace binary?

### ISSUE THREAD

**Issue by jeez** [facebookexperimental/ExtendedAndroidTools#42]
Hi there @michalgr @danielocfb! Do we have public instructions around how to build bpftrace for Android statically? If not, any chance that could be documented as part of this project?

thanks a lot

**Comment by danielocfb** [comment]
Hi Jesus, I *believe* https://github.com/danielocfb/bpftrace_local_manifest contains all the information you'd need.

**Comment by michalgr** [comment]
Hi @jeez!

The easiest way to get static bpftrace binaries for android is to download the CI builds, for example from here: https://github.com/facebookexperimental/ExtendedAndroidTools/actions/runs/4785564960 (bpftrace-android-*). You should be able to build static binaries on your own, just run the following command in the provided Docker environment: `make bpftrace STATIC_LINKING=true LLVM_BPF_ONLY=true`

**Comment by simpleton** [comment]
+1 on @michalgr's method. The bpftrace_local_manifest is hard to maintain since the c++ runtime's ABIs are not 100% compatible on different versions' LLVM.

**Comment by jeez** [comment]
thanks, all, that worked! I will be in touch.
