### ISSUE TITLE
lastest bpftrace need -lstdc++fs

### ISSUE THREAD

**Issue by b-ripper** [facebookexperimental/ExtendedAndroidTools#5]
Hi,

The lastest bpftrace master need -lstdc++fs, current env not supported.
I found libc++fs is available on Android R AOSP source code(external/libcxx).
also available in projects/llvm/sources/libcxx.

So, use libc++fs instead of libstdc++fs?
Do you have any suggestion? 

Very thanks

**Comment by michalgr** [comment]
So there are a few things we could try.

`std::filesystem` will be supported in ndk r22, at least according to this issue: https://github.com/android/ndk/issues/609. But we're on r17 here for a reason (r18 removed gcc and libelf does not build with clang). Plus it's not obvious whether `std::filesystem` will be available on all the platforms we support (API 28+). The best way forward would be to move to r22 (if that works), but it won't happen soon.

Another way is to do what you suggest. We can compile our own libc++ as you suggest and link against that. It seems that we should be able to set [`ANDROID_STL`](https://developer.android.com/ndk/guides/cmake#android_stl) to none to prevent ndk from providing its own stl.

I wonder whether we can do something quick to unblock you sooner. How much of libstdc++fs do we actually need ? Maybe we can just define our own `filesystem` header and define `absolute` and `canonical` functions in terms of `realpath` ?

**Comment by michalgr** [comment]
I just pushed 2b28f5ef9e87b6a9d17801b3f6c460e7b0cf95a1 which updates version of bpftrace to current master. @b-ripper: does it solve problems you run into ?

**Comment by b-ripper** [comment]
Yes, thanks very much!
